name       : harfbuzz
version    : 1.8.2
release    : 26
source     :
    - https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.8.2.tar.bz2 : c8a3f88f416185a82f899a68b5714d6a40d7dc4d1d7379057348918d55aac657
license    :
    - MIT
    - HPND
component  : xorg.fonts
summary    : HarfBuzz is a text shaping library
description: |
    HarfBuzz is a software development library for text shaping, which is the process of converting Unicode text to glyph indices and positions.
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(graphite2)
    - pkgconfig32(icu-io)
emul32     : yes
setup      : |
    %configure --disable-static --with-graphite2
build      : |
    %make
install    : |
    %make_install
check      : |
    # tests are failing on the build server
    %make check || :
