name       : harfbuzz
version    : 2.6.4
release    : 35
source     :
    - https://github.com/harfbuzz/harfbuzz/releases/download/2.6.4/harfbuzz-2.6.4.tar.xz : 9413b8d96132d699687ef914ebb8c50440efc87b3f775d25856d7ec347c03c12
license    :
    - MIT
    - HPND
component  : xorg.fonts
summary    : HarfBuzz is a text shaping library
description: |
    HarfBuzz is a software development library for text shaping, which is the process of converting Unicode text to glyph indices and positions.
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(graphite2)
    - pkgconfig32(icu-io)
emul32     : yes
optimize   : lto
setup      : |
    %configure --disable-static --with-graphite2
build      : |
    %make
install    : |
    %make_install
check      : |
    # tests are failing on the build server
    %make check || :
