name       : harfbuzz
version    : 2.8.2
release    : 48
source     :
    - https://github.com/harfbuzz/harfbuzz/releases/download/2.8.2/harfbuzz-2.8.2.tar.xz : d58461395ce28b9dc03903254374dd70c38c8c28c5046db123c08f7ab9417be7
license    :
    - MIT
    - HPND
component  : xorg.fonts
summary    : HarfBuzz is a text shaping library
description: |
    HarfBuzz is a software development library for text shaping, which is the process of converting Unicode text to glyph indices and positions.
emul32     : yes
optimize   : lto
autodep    : no
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(graphite2)
    - pkgconfig32(icu-io)
rundeps    :
    - glib2
    - glibc
    - graphite2
    - libicu
    - 32bit :
        - glib2-32bit
        - glibc-32bit
        - graphite2-32bit
        - harfbuzz
        - libgcc-32bit
    - 32bit-devel :
        - glib2-32bit-devel
        - graphite2-32bit-devel
        - harfbuzz-devel
        - libicu-32bit-devel
    - devel :
        - glib2-devel
        - graphite2-devel
        - libicu-devel
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi

    %meson_configure -Dbenchmark=disabled -Dgraphite=enabled -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
