name       : harfbuzz
version    : 8.0.1
release    : 60
source     :
    - https://github.com/harfbuzz/harfbuzz/releases/download/8.0.1/harfbuzz-8.0.1.tar.xz : c1ce780acd385569f25b9a29603d1d5bc71e6940e55bfdd4f7266fad50e42620
license    :
    - MIT
    - HPND
component  : xorg.fonts
summary    : HarfBuzz is a text shaping library
description: |
    HarfBuzz is a software development library for text shaping, which is the process of converting Unicode text to glyph indices and positions.
emul32     : yes
optimize   : lto
autodep    : no
builddeps  :
    - pkgconfig32(freetype2)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(graphite2)
    - pkgconfig32(icu-io)
rundeps    :
    - glib2
    - glibc
    - graphite2
    - libicu
    - 32bit :
        - glib2-32bit
        - glibc-32bit
        - graphite2-32bit
        - harfbuzz
        - libgcc-32bit
    - 32bit-devel :
        - glib2-32bit-devel
        - graphite2-32bit-devel
        - harfbuzz-devel
        - libicu-32bit-devel
    - devel :
        - glib2-devel
        - graphite2-devel
        - libicu-devel
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi

    %meson_configure -Dbenchmark=disabled -Dgraphite=enabled -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
