name       : harfbuzz
version    : 1.5.1
release    : 15
source     :
    - https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.5.1.tar.bz2 : 56838dfdad2729b8866763c82d623354d138a4d99d9ffb710c7d377b5cfc7c51
license    :
    - MIT
    - HPND
component  : xorg.fonts
summary    : International Components for Unicode
description: |
    The International Components for Unicode (ICU) package is a mature, widely used set of C/C++ libraries providing Unicode and Globalization support for software applications. ICU is widely portable and gives applications the same results on all platforms.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig32(icu-io)
    - pkgconfig(fontconfig)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig(graphite2)
    - pkgconfig32(graphite2)
    - pkgconfig32(glib-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
setup      : |
    %configure --disable-static --with-graphite2 --prefix=/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
