name       : harfbuzz
version    : 1.4.5
release    : 13
source     :
    - https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.4.5.tar.bz2 : d0e05438165884f21658154c709075feaf98c93ee5c694b951533ac425a9a711
license    :
    - MIT
    - HPND
component  : xorg.fonts
summary    : International Components for Unicode
description: |
    The International Components for Unicode (ICU) package is a mature, widely used set of C/C++ libraries providing Unicode and Globalization support for software applications. ICU is widely portable and gives applications the same results on all platforms.
builddeps  :
    - pkgconfig(icu-io)
    - pkgconfig32(icu-io)
    - pkgconfig(fontconfig)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig(graphite2)
    - pkgconfig32(graphite2)
    - pkgconfig32(glib-2.0)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32     : yes
setup      : |
    %configure --disable-static --with-graphite2 --prefix=/usr
build      : |
    %make
install    : |
    %make_install
